FIND_PATH( Orz_Asio_DIR 
  bin/debug
  PATHS 
  ${PROJECT_SOURCE_DIR}
  ${PROJECT_SOURCE_DIR}/OrzSDK
  ${PROJECT_SOURCE_DIR}/build/OrzSDK
  ${PROJECT_SOURCE_DIR}/../build/OrzSDK
  ${PROJECT_SOURCE_DIR}/../../build/OrzSDK
  ${PROJECT_BINARY_DIR}
  ${PROJECT_BINARY_DIR}/OrzSDK
  ${PROJECT_BINARY_DIR}/build/OrzSDK
  ${PROJECT_BINARY_DIR}/../build/OrzSDK
  ${PROJECT_BINARY_DIR}/../../build/OrzSDK
  NO_DEFAULT_PATH
)
